import { ArrowRight, FileText, Route, ShieldCheck } from "lucide-react";
import Navbar from "../components/Navbar";
import { catalog, money } from "../lib/catalog";

export default function CartPage() {
  const items = catalog.slice(0, 2);
  const subtotal = items.reduce((sum, item) => sum + item.price, 0);
  return <main className="min-h-screen bg-black px-5 pb-20 pt-36 text-white md:px-10"><Navbar /><div className="mx-auto max-w-6xl"><header className="border-b border-white/15 pb-7"><p className="font-mono text-xs tracking-[.3em] text-cyan-300">04 / Ledger Engine</p><h1 className="mt-3 text-5xl font-semibold">Transaction manifest<span className="text-cyan-300">.</span></h1></header><div className="mt-8 grid grid-cols-1 gap-6 lg:grid-cols-[1.5fr_.8fr]"><section className="border border-white/10 bg-slate-950/60"><div className="flex items-center justify-between border-b border-white/10 p-5 font-mono text-xs text-slate-500"><span>LEDGER_ID: RC-2026-0042</span><FileText className="h-4 w-4 text-cyan-300" /></div>{items.map((item, index) => <div key={item.id} className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b border-white/5 p-5"><span className="font-mono text-xs text-slate-600">0{index + 1}</span><div><h2 className="font-semibold">{item.name}</h2><p className="mt-1 font-mono text-xs text-slate-500">ROUTE / SECURE_ASSET_CHANNEL</p></div><strong className="font-mono">{money(item.price)}</strong></div>)}<div className="flex items-center gap-3 p-5 font-mono text-xs text-emerald-300"><Route className="h-4 w-4" /> SHIPPING_ROUTE: GLOBAL_PRIORITY // ETA 48H</div></section><aside className="border border-cyan-300/20 bg-cyan-950/10 p-6"><p className="font-mono text-xs text-slate-500">EXECUTION SEQUENCE</p><div className="mt-6 space-y-4 font-mono text-xs"><p className="text-emerald-300">01 // ITEMS VERIFIED</p><p className="text-emerald-300">02 // ROUTING RESERVED</p><p className="text-slate-500">03 // PAYMENT PENDING</p></div><div className="mt-10 border-t border-white/10 pt-5"><span className="font-mono text-xs text-slate-500">TOTAL_SETTLEMENT</span><strong className="mt-2 block text-3xl">{money(subtotal)}</strong><button className="mt-6 flex w-full items-center justify-center gap-2 bg-cyan-300 px-4 py-4 font-mono text-sm font-bold text-black hover:bg-cyan-200">Authorize checkout <ArrowRight className="h-4 w-4" /></button></div><div className="mt-5 flex items-center gap-2 font-mono text-[10px] text-slate-500"><ShieldCheck className="h-4 w-4 text-emerald-300" /> Encrypted settlement channel</div></aside></div></div></main>;
}
