services:
  - type: web
    name: retail-logistics-core
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn mywork.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: DATABASE_URL
        fromDatabase:
          name: postgres_db
          property: connectionString
    envVarDefaults:
      DEBUG: "False"
databases:
  - name: postgres_db
    databaseName: retail_db
    user: postgres
    ipAllowList: []
