"use client";

import { motion } from "framer-motion";
import { Fingerprint, ScanFace, ShieldCheck } from "lucide-react";
import { useState } from "react";
import Navbar from "../components/Navbar";

export default function AuthPage() {
  const [mode, setMode] = useState<"login" | "register">("login");
  const [scanning, setScanning] = useState(false);
  function authenticate(event: React.FormEvent) { event.preventDefault(); setScanning(true); window.setTimeout(() => setScanning(false), 1800); }
  return <main className="min-h-screen bg-black px-5 pb-20 pt-36 text-white"><Navbar /><div className="mx-auto grid min-h-[70vh] max-w-5xl place-items-center"><div className="grid w-full overflow-hidden border border-white/10 bg-white/[.03] backdrop-blur-xl md:grid-cols-2"><section className="hidden border-r border-white/10 p-10 md:block"><p className="font-mono text-xs tracking-[.3em] text-cyan-300">05 / Gateway Portal</p><h1 className="mt-20 text-5xl font-semibold">Identity is<br /><span className="text-cyan-300">the first key.</span></h1><div className="mt-20 flex items-center gap-4 font-mono text-xs text-emerald-300"><ShieldCheck className="h-5 w-5" /> RED/CART_OS SECURE ACCESS</div></section><section className="p-7 md:p-10"><div className="mb-8 flex items-center justify-between"><div><p className="font-mono text-xs text-slate-500">AUTH_PROTOCOL // {mode.toUpperCase()}</p><h2 className="mt-2 text-2xl font-semibold">{mode === "login" ? "Welcome back" : "Initialize identity"}</h2></div><button onClick={() => setMode(mode === "login" ? "register" : "login")} className="font-mono text-xs text-cyan-300">{mode === "login" ? "Register" : "Login"}</button></div>{scanning ? <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="grid min-h-72 place-items-center text-center"><Fingerprint className="h-20 w-20 animate-pulse text-cyan-300" /><p className="mt-5 font-mono text-xs tracking-widest text-emerald-300">BIOMETRIC SCAN IN PROGRESS...</p></motion.div> : <form onSubmit={authenticate} className="space-y-5"><label className="block"><span className="font-mono text-xs text-slate-500">IDENTIFIER</span><input type={mode === "login" ? "email" : "text"} required className="mt-2 w-full border border-white/15 bg-black/50 px-4 py-3 text-white outline-none transition focus:border-cyan-300 focus:shadow-[0_0_20px_rgba(6,182,212,.2)]" placeholder={mode === "login" ? "operator@redcart.os" : "operator_id"} /></label><label className="block"><span className="font-mono text-xs text-slate-500">ACCESS_KEY</span><input type="password" required className="mt-2 w-full border border-white/15 bg-black/50 px-4 py-3 text-white outline-none transition focus:border-cyan-300 focus:shadow-[0_0_20px_rgba(6,182,212,.2)]" placeholder="••••••••••" /></label>{mode === "register" && <label className="block"><span className="font-mono text-xs text-slate-500">REPEAT_KEY</span><input type="password" required className="mt-2 w-full border border-white/15 bg-black/50 px-4 py-3 text-white outline-none transition focus:border-cyan-300 focus:shadow-[0_0_20px_rgba(6,182,212,.2)]" /></label>}<button className="flex w-full items-center justify-center gap-2 bg-cyan-300 px-4 py-4 font-mono text-sm font-bold text-black hover:bg-cyan-200"><ScanFace className="h-4 w-4" /> Authenticate</button></form>}</section></div></div></main>;
}
