"use client";

import { motion } from "framer-motion";
import { Activity, ArrowUpRight, Database, ScanLine } from "lucide-react";
import Link from "next/link";
import Navbar from "../components/Navbar";
import { catalog, money } from "../lib/catalog";

export default function ShopPage() {
  return <main className="min-h-screen bg-black px-5 pb-20 pt-36 text-white md:px-10"><Navbar /><div className="mx-auto max-w-7xl"><header className="mb-12 flex flex-col justify-between gap-6 border-b border-white/10 pb-8 md:flex-row md:items-end"><div><p className="font-mono text-xs uppercase tracking-[.3em] text-cyan-300">02 / Metadata Shop</p><h1 className="mt-3 text-5xl font-semibold tracking-tight md:text-7xl">Asset index<span className="text-cyan-300">.</span></h1></div><div className="flex items-center gap-3 font-mono text-xs text-emerald-300"><Activity className="h-4 w-4" /> INVENTORY LINK: LIVE</div></header><div className="border-t border-white/10">{catalog.map((product, index) => <motion.article key={product.id} initial={{ opacity: 0, x: -16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .08 }} className="group relative flex flex-col justify-between gap-4 border-b border-white/5 py-4 transition hover:border-cyan-300/50 hover:bg-cyan-950/10 md:flex-row md:items-center"><div className="flex min-w-0 items-center gap-4 md:w-[42%]"><span className="font-mono text-xs text-slate-600">0{index + 1}</span><div className="relative h-16 w-20 shrink-0 overflow-hidden border border-white/10"><img src={product.image} alt={product.name} className="h-full w-full object-cover grayscale transition duration-500 group-hover:scale-110 group-hover:grayscale-0" /><ScanLine className="absolute right-1 top-1 h-3 w-3 text-cyan-300" /></div><div className="min-w-0"><p className="truncate font-mono text-[10px] uppercase tracking-widest text-cyan-300">{product.category}</p><h2 className="truncate text-lg font-semibold">{product.name}</h2></div></div><div className="flex flex-wrap items-center gap-5 font-mono text-xs md:w-[38%] md:justify-end"><span className="text-slate-500">SKU_{product.id.toUpperCase()}</span><span className="flex items-center gap-2 text-emerald-300"><Database className="h-3 w-3" /> {product.inventory} units</span><span className="text-slate-300">{money(product.price)}</span></div><Link href={`/shop/${product.id}`} className="flex shrink-0 items-center gap-2 border border-white/10 px-3 py-2 font-mono text-xs text-cyan-300 transition hover:border-cyan-300/60 hover:bg-cyan-300/10">Inspect <ArrowUpRight className="h-4 w-4" /></Link><div className="pointer-events-none absolute left-24 top-full z-10 hidden w-72 border border-cyan-300/30 bg-black/95 p-4 shadow-[0_0_30px_rgba(6,182,212,.12)] group-hover:block"><p className="font-mono text-[10px] text-cyan-300">TECHNICAL SPECIFICATION MATRIX</p>{product.specs.map((spec) => <p key={spec} className="mt-2 font-mono text-xs text-slate-400">// {spec}</p>)}</div></motion.article>)}</div></div></main>;
}
