"use client";

import { motion } from "framer-motion";
import { ArrowUpRight, Crosshair, Database, ScanLine } from "lucide-react";
import Link from "next/link";
import { catalog, money } from "../lib/catalog";
import Navbar from "../components/Navbar";

export default function ShopPage() {
  return <main className="min-h-screen bg-black px-5 pb-20 pt-36 text-white md:px-10"><Navbar /><div className="mx-auto max-w-7xl"><header className="mb-12 border-l-2 border-cyan-300 pl-5"><p className="font-mono text-xs uppercase tracking-[.3em] text-cyan-300">02 / Metadata Shop</p><h1 className="mt-3 text-5xl font-semibold tracking-tight md:text-7xl">Asset index<span className="text-cyan-300">.</span></h1><p className="mt-4 max-w-xl text-slate-400">A living catalog of objects selected for precision, utility, and signal quality.</p></header><div className="grid grid-cols-1 gap-4 md:grid-cols-12">{catalog.map((product, index) => <motion.article key={product.id} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .08 }} className={`group relative overflow-hidden border border-white/10 bg-slate-950/70 ${index === 0 ? "md:col-span-7 md:row-span-2" : "md:col-span-5"}`}><div className="relative min-h-[320px] overflow-hidden"><img src={product.image} alt={product.name} className="absolute inset-0 h-full w-full object-cover opacity-70 grayscale transition duration-700 group-hover:scale-105 group-hover:grayscale-0" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/20 to-transparent" /><ScanLine className="absolute right-5 top-5 h-5 w-5 text-cyan-300" /><div className="absolute bottom-0 w-full p-6"><p className="font-mono text-xs uppercase tracking-widest text-cyan-300">{product.category}</p><h2 className="mt-2 text-2xl font-semibold">{product.name}</h2><div className="mt-3 flex items-center justify-between"><span className="font-mono text-lg">{money(product.price)}</span><Link href={`/shop/${product.id}`} className="flex items-center gap-2 font-mono text-xs text-cyan-300">Inspect <ArrowUpRight className="h-4 w-4" /></Link></div></div></div><div className="absolute inset-x-0 bottom-0 translate-y-full border-t border-cyan-300/30 bg-black/90 p-5 transition-transform duration-500 group-hover:translate-y-0"><div className="flex items-center gap-2 font-mono text-xs text-emerald-300"><Database className="h-4 w-4" /> {product.status}</div><div className="mt-3 flex flex-wrap gap-2">{product.specs.map((spec) => <span key={spec} className="border border-white/10 px-2 py-1 font-mono text-[10px] text-slate-400">{spec}</span>)}</div></div><Crosshair className="absolute left-4 top-4 h-5 w-5 text-white/40" /></motion.article>)}</div></div></main>;
}
