import { Activity, Crosshair, Database, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import Navbar from "../../components/Navbar";
import { catalog, money } from "../../lib/catalog";

export function generateStaticParams() { return catalog.map((product) => ({ id: product.id })); }

export default async function DiagnosticsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const product = catalog.find((item) => item.id === id);
  if (!product) notFound();
  return <main className="min-h-screen bg-black px-5 pb-20 pt-36 text-white md:px-10"><Navbar /><div className="mx-auto max-w-7xl"><Link href="/shop" className="font-mono text-xs text-cyan-300">← return to asset index</Link><div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-2"><section className="relative min-h-[620px] overflow-hidden border border-cyan-300/20 bg-slate-950/70"><img src={product.image} alt={product.name} className="h-full min-h-[620px] w-full object-cover opacity-75" /><div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-black/20" /><div className="absolute inset-10 border border-cyan-300/30"><Crosshair className="absolute -left-3 -top-3 h-6 w-6 bg-black text-cyan-300" /><Crosshair className="absolute -bottom-3 -right-3 h-6 w-6 rotate-180 bg-black text-cyan-300" /></div><div className="absolute bottom-8 left-8 font-mono text-xs text-cyan-300">MEDIA_CHANNEL // LOCKED<br /><span className="text-slate-500">FRAME_01 / OBJECT_AUTHENTICATED</span></div></section><section className="border border-white/10 bg-white/[.035] p-7 backdrop-blur-xl md:p-10"><p className="font-mono text-xs uppercase tracking-[.3em] text-cyan-300">Diagnostics Lab // {product.id}</p><h1 className="mt-5 text-5xl font-semibold tracking-tight">{product.name}</h1><p className="mt-3 font-mono text-xl text-slate-300">{money(product.price)}</p><div className="mt-10 space-y-4 border-y border-white/10 py-6 font-mono text-xs">{product.specs.map((spec, index) => <div key={spec} className="flex justify-between gap-5"><span className="text-slate-500">SPEC_0{index + 1}</span><strong className="text-right text-cyan-200">{spec}</strong></div>)}<div className="flex justify-between gap-5"><span className="text-slate-500">STOCK_TELEMETRY</span><strong className="text-emerald-300">{product.status}</strong></div></div><div className="mt-10 grid grid-cols-2 gap-3"><div className="border border-white/10 p-4"><Activity className="h-4 w-4 text-cyan-300" /><p className="mt-4 font-mono text-xs text-slate-500">LATENCY</p><strong className="text-xl">24ms</strong></div><div className="border border-white/10 p-4"><ShieldCheck className="h-4 w-4 text-emerald-300" /><p className="mt-4 font-mono text-xs text-slate-500">AUTHENTICITY</p><strong className="text-xl text-emerald-300">99.9%</strong></div></div><button className="mt-8 flex w-full items-center justify-center gap-2 bg-cyan-300 px-5 py-4 font-mono text-sm font-bold text-black transition hover:bg-cyan-200"><Database className="h-4 w-4" /> Commit to vault</button></section></div></div></main>;
}
