# Generated by Django 5.2.4 on 2025-07-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
