# Generated by Django 6.0.4 on 2026-04-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0007_contactformsubmission_discountcode_emailtemplate_faq_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale_ends_at",
            field=models.DateTimeField(
                blank=True, help_text="End time for flash sale", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.FloatField(
                blank=True, help_text="Sale price for flash sale", null=True
            ),
        ),
    ]
