# Generated by Django 5.2.12 on 2026-05-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_systemalert_notification_notificationlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Home', 'Home & Kitchen'), ('Sports', 'Sports & Outdoors'), ('Books', 'Books'), ('Toys', 'Toys & Games'), ('Accessories', 'Accessories'), ('Fashion', 'Fashion'), ('Fitness', 'Fitness'), ('Gaming', 'Gaming'), ('Home Appliances', 'Home Appliances'), ('Laptops', 'Laptops'), ('Phones', 'Phones'), ('Sneakers', 'Sneakers'), ('Watches', 'Watches'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
