# Generated by Django 5.1.4 on 2026-07-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='escrow_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='escrow_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='escrow_status',
            field=models.CharField(choices=[('pending', 'Pending Escrow'), ('held', 'Held in Escrow'), ('released', 'Released to Seller'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
    ]
