# Generated by Django 5.2.12 on 2026-07-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='insurance_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='insurance_opted',
            field=models.BooleanField(default=False),
        ),
    ]
